# Generated by Django 4.2.11 on 2026-05-17 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_schedule_type_task_scheduled_for'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0002_transaction_econfirm_checkout_request_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_month', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('WAIVED', 'Waived'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('due_date', models.DateTimeField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tasker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('tasker', 'billing_month')},
            },
        ),
        migrations.CreateModel(
            name='PlatformFeeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('billing_month', models.DateField()),
                ('is_trial_usage', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('TRACKED', 'Tracked'), ('INVOICED', 'Invoiced'), ('WAIVED', 'Waived')], default='TRACKED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usages', to='payments.platforminvoice')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_fee_usages', to='tasks.task')),
                ('tasker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_fee_usages', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='platform_fee_usage', to='payments.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
