# Generated by Django 4.2.11 on 2026-05-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_location_latitude_task_location_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='schedule_type',
            field=models.CharField(choices=[('ASAP', 'As soon as possible'), ('SCHEDULED', 'Scheduled')], default='ASAP', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
