# Generated by Django 4.2.11 on 2026-05-17 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_groups_alter_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_kyc_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='KYCVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_front_image', models.ImageField(upload_to='kyc/id_fronts/')),
                ('id_back_image', models.ImageField(upload_to='kyc/id_backs/')),
                ('live_face_image', models.ImageField(blank=True, null=True, upload_to='kyc/live_faces/')),
                ('extracted_full_name', models.CharField(blank=True, max_length=255)),
                ('extracted_student_id', models.CharField(blank=True, max_length=64)),
                ('extracted_department', models.CharField(blank=True, max_length=255)),
                ('extracted_school', models.CharField(blank=True, max_length=255)),
                ('extracted_degree', models.CharField(blank=True, max_length=255)),
                ('stamp_detected', models.BooleanField(default=False)),
                ('id_photo_detected', models.BooleanField(default=False)),
                ('face_match_confidence', models.DecimalField(blank=True, decimal_places=2, help_text='Confidence percentage from 0.00 to 100.00.', max_digits=5, null=True)),
                ('ocr_raw_response', models.JSONField(blank=True, default=dict)),
                ('face_match_raw_response', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('PENDING_REVIEW', 'Pending Review'), ('NEEDS_RETRY', 'Needs Retry'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING_REVIEW', max_length=20)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
