# Generated by Django 4.2.11 on 2026-05-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_kyc_verified_kycverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycverification',
            name='extracted_date_of_birth',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='extracted_expiration_date',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='extracted_issue_date',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='extracted_university_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='extracted_validity_period',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
