# Generated by Django 4.2.11 on 2026-05-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_availability_note_user_availability_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycverification',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('PENDING_REVIEW', 'Pending Review'), ('NEEDS_RETRY', 'Needs Retry'), ('FACE_MISMATCH', 'Face Mismatch'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING_REVIEW', max_length=20),
        ),
    ]
