# Generated by Django 4.2.11 on 2026-05-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_kycverification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycverification',
            name='id_back_image',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/id_backs/'),
        ),
    ]
