# Generated by Django 4.2.11 on 2026-05-17 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_schedule_type_task_scheduled_for'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('HARASSMENT', 'Harassment or abusive behaviour'), ('SAFETY_CONCERN', 'Safety concern'), ('NO_SHOW', 'Did not show up'), ('POOR_WORK', 'Poor or slow work'), ('PAYMENT_ISSUE', 'Payment issue'), ('INAPPROPRIATE_CONTENT', 'Inappropriate content'), ('OTHER', 'Other')], max_length=40)),
                ('details', models.TextField(max_length=1000)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('REVIEWING', 'Reviewing'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], default='OPEN', max_length=20)),
                ('is_public', models.BooleanField(default=False, help_text='Only publish after admin moderation.')),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_submitted', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_reports', to='tasks.task')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('reporter', 'reported_user', 'task', 'reason')},
            },
        ),
    ]
